### ISSUE TITLE
Difference between previous MoM code and presented code

### ISSUE THREAD

**Issue by kapil-iitk** [wanygen/mom-conical-array#1]
Hello, can you share what is the difference ( in the program) between previous MoM code and present code?

Thanks

**Comment by bdebye** [comment]
This version of code mainly changed its dependency on linear algebra package from blitz to eigen. The eigen library provides C++ encapsulation of intel's math kernel library so it runs blazingly faster than previous program when linked against MKL.

**Comment by kapil-iitk** [comment]
Thank you for the comment. I am using code::Blocks to compile the program in windows (windows 8.1 64 bit) environment. I downloaded the eigen library and paste to in include folder. While compiling, it showing error mkl.h is not available (missing). Through some other sources I come to know that by editing type.h file and replacing #define EIGEN_USE_MKL_ALL  with  #define EIGEN_USE_LAPACKE_STRICT it is possible to run the program. But I am enable to compile the program. Can you share your setting and procedure with us.

**Comment by bdebye** [comment]
The "mkl.h" is the header file of Intel's Math Kernel Library, while the MKL library is distributed with Intel's C++/FORTRAN compilers. The library can also be obtained with a community license, but I reckon that the linking against non-intel compilers can be very complicated. The Eigen library has its own implementation of linear algebra algorithms, however, when certain macros are defined, the library will use the BLAS/LAPACK  or MKL versions of those algorithms instead, because they are generally more efficient. The official document of Eigen explained its [usage](http://eigen.tuxfamily.org/dox/TopicUsingIntelMKL.html). Nevertheless, you can use EIgen's own implementation by deleting all the related macros.

The MOM code uses meshes generated by the [Gmsh](http://gmsh.info/) software, the program will read in the mesh file and then parse the triangle pairs from the mesh. The computation of impedance is very complex and is roughly the core part of this code. And next, the corresponding linear system will be solved. Finally, you can compute every parameter you like using the current distribution. If you want to test, I suggest you replace the `conical_array.msh` with something smaller generated by Gmsh, since it is a very large problem and it may take days to solve it even using a workstation. In addition, you must specify the indexes of a pair of triangle used for excitation by making the feed gap the only segment element in the mesh when processing radiation problems. You can refer to the documentation of Gmsh for details about its usage.

Sorry for the crudeness of this code because I wrote it primarily for my own use in the laboratory, so you must tweak it a bit to make the program work.

**Comment by kapil-iitk** [comment]
Thank you very much for your response.

**Comment by kapil-iitk** [comment]
I tried a lot to run this code. But unfortunately, this is not working for me. Can you suggest me how to use native eigen module for the code compilation.

**Comment by bdebye** [comment]
What do you usually use for instant messaging? Skype?

**Comment by kapil-iitk** [comment]
Yes.

**Comment by bdebye** [comment]
I am downloading skype
